// SPDX-License-Identifier: Apache-2.0

//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Budget) DeepCopyInto(out *Budget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Budget.
func (in *Budget) DeepCopy() *Budget {
	if in == nil {
		return nil
	}
	out := new(Budget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Classification) DeepCopyInto(out *Classification) {
	*out = *in
	if in.Shadow != nil {
		in, out := &in.Shadow, &out.Shadow
		*out = make([]ShadowVerdict, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Classification.
func (in *Classification) DeepCopy() *Classification {
	if in == nil {
		return nil
	}
	out := new(Classification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Narration) DeepCopyInto(out *Narration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Narration.
func (in *Narration) DeepCopy() *Narration {
	if in == nil {
		return nil
	}
	out := new(Narration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PullRequestRef) DeepCopyInto(out *PullRequestRef) {
	*out = *in
	if in.ArmedAt != nil {
		in, out := &in.ArmedAt, &out.ArmedAt
		*out = (*in).DeepCopy()
	}
	if in.MergedAt != nil {
		in, out := &in.MergedAt, &out.MergedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PullRequestRef.
func (in *PullRequestRef) DeepCopy() *PullRequestRef {
	if in == nil {
		return nil
	}
	out := new(PullRequestRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunRecord) DeepCopyInto(out *RunRecord) {
	*out = *in
	if in.Started != nil {
		in, out := &in.Started, &out.Started
		*out = (*in).DeepCopy()
	}
	if in.Finished != nil {
		in, out := &in.Finished, &out.Finished
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunRecord.
func (in *RunRecord) DeepCopy() *RunRecord {
	if in == nil {
		return nil
	}
	out := new(RunRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShadowVerdict) DeepCopyInto(out *ShadowVerdict) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShadowVerdict.
func (in *ShadowVerdict) DeepCopy() *ShadowVerdict {
	if in == nil {
		return nil
	}
	out := new(ShadowVerdict)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Source) DeepCopyInto(out *Source) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Source.
func (in *Source) DeepCopy() *Source {
	if in == nil {
		return nil
	}
	out := new(Source)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Task) DeepCopyInto(out *Task) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Task.
func (in *Task) DeepCopy() *Task {
	if in == nil {
		return nil
	}
	out := new(Task)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Task) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskList) DeepCopyInto(out *TaskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Task, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskList.
func (in *TaskList) DeepCopy() *TaskList {
	if in == nil {
		return nil
	}
	out := new(TaskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TaskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskSpec) DeepCopyInto(out *TaskSpec) {
	*out = *in
	out.Source = in.Source
	out.Budget = in.Budget
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskSpec.
func (in *TaskSpec) DeepCopy() *TaskSpec {
	if in == nil {
		return nil
	}
	out := new(TaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskStatus) DeepCopyInto(out *TaskStatus) {
	*out = *in
	if in.PhaseSince != nil {
		in, out := &in.PhaseSince, &out.PhaseSince
		*out = (*in).DeepCopy()
	}
	if in.Classification != nil {
		in, out := &in.Classification, &out.Classification
		*out = new(Classification)
		(*in).DeepCopyInto(*out)
	}
	if in.Runs != nil {
		in, out := &in.Runs, &out.Runs
		*out = make([]RunRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PullRequest != nil {
		in, out := &in.PullRequest, &out.PullRequest
		*out = new(PullRequestRef)
		(*in).DeepCopyInto(*out)
	}
	out.Usage = in.Usage
	if in.Narrated != nil {
		in, out := &in.Narrated, &out.Narrated
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Outbox != nil {
		in, out := &in.Outbox, &out.Outbox
		*out = make([]Narration, len(*in))
		copy(*out, *in)
	}
	if in.Handled != nil {
		in, out := &in.Handled, &out.Handled
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
	if in.LastActivity != nil {
		in, out := &in.LastActivity, &out.LastActivity
		*out = (*in).DeepCopy()
	}
	if in.Trace != nil {
		in, out := &in.Trace, &out.Trace
		*out = new(TraceRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskStatus.
func (in *TaskStatus) DeepCopy() *TaskStatus {
	if in == nil {
		return nil
	}
	out := new(TaskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TraceRef) DeepCopyInto(out *TraceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TraceRef.
func (in *TraceRef) DeepCopy() *TraceRef {
	if in == nil {
		return nil
	}
	out := new(TraceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Usage) DeepCopyInto(out *Usage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Usage.
func (in *Usage) DeepCopy() *Usage {
	if in == nil {
		return nil
	}
	out := new(Usage)
	in.DeepCopyInto(out)
	return out
}
