apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-factory-config
  labels: {{- include "agent-factory.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
